export const ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_PASSWORD_INVALID: "AUTH_PASSWORD_INVALID",
  AUTH_CHALLENGE_INVALID: "AUTH_CHALLENGE_INVALID",
  AUTH_CHALLENGE_EXPIRED: "AUTH_CHALLENGE_EXPIRED",
  AUTH_INVALID_ENCRYPTED_PASSWORD: "AUTH_INVALID_ENCRYPTED_PASSWORD",
  TOKEN_SCOPE_FORBIDDEN: "TOKEN_SCOPE_FORBIDDEN",
  TOKEN_NAME_REQUIRED: "TOKEN_NAME_REQUIRED",
  TOKEN_SCOPE_REQUIRED: "TOKEN_SCOPE_REQUIRED",
  TOKEN_CREATE_FAILED: "TOKEN_CREATE_FAILED",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  TOKEN_UNAUTHORIZED: "TOKEN_UNAUTHORIZED",
  TOKEN_PROJECT_FORBIDDEN: "TOKEN_PROJECT_FORBIDDEN",
  TOKEN_OWNER_REQUIRED: "TOKEN_OWNER_REQUIRED",
  TOKEN_RATE_LIMITED: "TOKEN_RATE_LIMITED",
  PROJECT_CREATE_FORBIDDEN: "PROJECT_CREATE_FORBIDDEN",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_NAME_REQUIRED: "PROJECT_NAME_REQUIRED",
  PROJECT_NO_REQUIRED: "PROJECT_NO_REQUIRED",
  PROJECT_NO_CONFLICT: "PROJECT_NO_CONFLICT",
  PROJECT_UPDATE_FAILED: "PROJECT_UPDATE_FAILED",
  PROJECT_ACCESS_DENIED: "PROJECT_ACCESS_DENIED",
  PROJECT_MEMBER_NOT_FOUND: "PROJECT_MEMBER_NOT_FOUND",
  PROJECT_MEMBER_EXISTS: "PROJECT_MEMBER_EXISTS",
  PROJECT_MEMBER_DELETE_FAILED: "PROJECT_MEMBER_DELETE_FAILED",
  PROJECT_MEMBER_ROLE_UNSUPPORTED: "PROJECT_MEMBER_ROLE_UNSUPPORTED",
  PROJECT_OWNER_IMMUTABLE: "PROJECT_OWNER_IMMUTABLE",
  PROJECT_KEY_GENERATE_FAILED: "PROJECT_KEY_GENERATE_FAILED",
  PROJECT_DISPLAY_CODE_CONFLICT: "PROJECT_DISPLAY_CODE_CONFLICT",
  PROJECT_DISPLAY_CODE_GENERATE_FAILED: "PROJECT_DISPLAY_CODE_GENERATE_FAILED",
  PROJECT_CONFLICT: "PROJECT_CONFLICT",
  PROJECT_INACTIVE: "PROJECT_INACTIVE",
  PROJECT_MODULE_CREATE_FAILED: "PROJECT_MODULE_CREATE_FAILED",
  PROJECT_MODULE_NOT_FOUND: "PROJECT_MODULE_NOT_FOUND",
  PROJECT_MODULE_PARENT_INVALID: "PROJECT_MODULE_PARENT_INVALID",
  PROJECT_MODULE_MEMBER_NOT_FOUND: "PROJECT_MODULE_MEMBER_NOT_FOUND",
  PROJECT_MODULE_MEMBER_EXISTS: "PROJECT_MODULE_MEMBER_EXISTS",
  PROJECT_ENVIRONMENT_CREATE_FAILED: "PROJECT_ENVIRONMENT_CREATE_FAILED",
  PROJECT_ENVIRONMENT_NOT_FOUND: "PROJECT_ENVIRONMENT_NOT_FOUND",
  PROJECT_VERSION_CREATE_FAILED: "PROJECT_VERSION_CREATE_FAILED",
  PROJECT_VERSION_NOT_FOUND: "PROJECT_VERSION_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ACCESS_DENIED: "USER_ACCESS_DENIED",
  SHARED_CONFIG_KEY_EXISTS: "SHARED_CONFIG_KEY_EXISTS",
  SHARED_CONFIG_NOT_FOUND: "SHARED_CONFIG_NOT_FOUND",
  SHARED_CONFIG_UPDATE_FAILED: "SHARED_CONFIG_UPDATE_FAILED",
  ISSUE_NOT_FOUND: "ISSUE_NOT_FOUND",
  ISSUE_UPDATE_FAILED: "ISSUE_UPDATE_FAILED",
  ISSUE_ACTION_FAILED: "ISSUE_ACTION_FAILED",
  ISSUE_INVALID_TRANSITION: "ISSUE_INVALID_TRANSITION",
  ISSUE_EDIT_FORBIDDEN: "ISSUE_EDIT_FORBIDDEN",
  ISSUE_ASSIGN_FORBIDDEN: "ISSUE_ASSIGN_FORBIDDEN",
  ISSUE_CLAIM_FORBIDDEN: "ISSUE_CLAIM_FORBIDDEN",
  ISSUE_ALREADY_ASSIGNED: "ISSUE_ALREADY_ASSIGNED",
  ISSUE_PARTICIPANT_FORBIDDEN: "ISSUE_PARTICIPANT_FORBIDDEN",
  ISSUE_START_FORBIDDEN: "ISSUE_START_FORBIDDEN",
  ISSUE_RESOLVE_FORBIDDEN: "ISSUE_RESOLVE_FORBIDDEN",
  ISSUE_VERIFY_FORBIDDEN: "ISSUE_VERIFY_FORBIDDEN",
  ISSUE_REOPEN_FORBIDDEN: "ISSUE_REOPEN_FORBIDDEN",
  ISSUE_CLOSE_FORBIDDEN: "ISSUE_CLOSE_FORBIDDEN",
  ISSUE_PARTICIPANT_EXISTS: "ISSUE_PARTICIPANT_EXISTS",
  ISSUE_PARTICIPANT_NOT_FOUND: "ISSUE_PARTICIPANT_NOT_FOUND",
  ISSUE_PARTICIPANT_DELETE_FAILED: "ISSUE_PARTICIPANT_DELETE_FAILED",
  ISSUE_ATTACHMENT_EXISTS: "ISSUE_ATTACHMENT_EXISTS",
  ISSUE_ATTACHMENT_NOT_FOUND: "ISSUE_ATTACHMENT_NOT_FOUND",
  ISSUE_ATTACHMENT_DELETE_FAILED: "ISSUE_ATTACHMENT_DELETE_FAILED",
  RD_STAGE_EXISTS: "RD_STAGE_EXISTS",
  RD_STAGE_NOT_FOUND: "RD_STAGE_NOT_FOUND",
  RD_STAGE_UPDATE_FAILED: "RD_STAGE_UPDATE_FAILED",
  RD_ITEM_NOT_FOUND: "RD_ITEM_NOT_FOUND",
  RD_ITEM_UPDATE_FAILED: "RD_ITEM_UPDATE_FAILED",
  RD_ITEM_DELETE_FAILED: "RD_ITEM_DELETE_FAILED",
  RD_ITEM_VERSION_CONFLICT: "RD_ITEM_VERSION_CONFLICT",
  RD_ACTION_FAILED: "RD_ACTION_FAILED",
  RD_INVALID_TRANSITION: "RD_INVALID_TRANSITION",
  RD_STAGE_FORBIDDEN: "RD_STAGE_FORBIDDEN",
  RD_ACCEPT_FORBIDDEN: "RD_ACCEPT_FORBIDDEN",
  RD_EDIT_FORBIDDEN: "RD_EDIT_FORBIDDEN",
  RD_DELETE_FORBIDDEN: "RD_DELETE_FORBIDDEN",
  RD_CLOSE_FORBIDDEN: "RD_CLOSE_FORBIDDEN",
  RD_PROGRESS_FORBIDDEN: "RD_PROGRESS_FORBIDDEN",
  RD_BLOCK_FORBIDDEN: "RD_BLOCK_FORBIDDEN",
  RD_ADVANCE_STAGE_FORBIDDEN: "RD_ADVANCE_STAGE_FORBIDDEN",
  RD_ADVANCE_STAGE_INVALID_STATUS: "RD_ADVANCE_STAGE_INVALID_STATUS",
  RD_ADVANCE_STAGE_INVALID_TARGET: "RD_ADVANCE_STAGE_INVALID_TARGET",
  RD_STAGE_PROJECT_MISMATCH: "RD_STAGE_PROJECT_MISMATCH",
  RD_ADVANCE_STAGE_FAILED: "RD_ADVANCE_STAGE_FAILED",
  FEEDBACK_NOT_FOUND: "FEEDBACK_NOT_FOUND",
  FEEDBACK_STATUS_UPDATE_FAILED: "FEEDBACK_STATUS_UPDATE_FAILED",
  ANNOUNCEMENT_NOT_FOUND: "ANNOUNCEMENT_NOT_FOUND",
  ANNOUNCEMENT_UPDATE_FAILED: "ANNOUNCEMENT_UPDATE_FAILED",
  ANNOUNCEMENT_PUBLISH_FAILED: "ANNOUNCEMENT_PUBLISH_FAILED",
  ANNOUNCEMENT_ARCHIVE_FAILED: "ANNOUNCEMENT_ARCHIVE_FAILED",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_SLUG_EXISTS: "DOCUMENT_SLUG_EXISTS",
  DOCUMENT_UPDATE_FAILED: "DOCUMENT_UPDATE_FAILED",
  DOCUMENT_PUBLISH_FAILED: "DOCUMENT_PUBLISH_FAILED",
  DOCUMENT_ARCHIVE_FAILED: "DOCUMENT_ARCHIVE_FAILED",
  RELEASE_NOT_FOUND: "RELEASE_NOT_FOUND",
  RELEASE_UPDATE_FAILED: "RELEASE_UPDATE_FAILED",
  RELEASE_PUBLISH_FAILED: "RELEASE_PUBLISH_FAILED",
  RELEASE_ARCHIVE_FAILED: "RELEASE_ARCHIVE_FAILED",
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
  AI_SQL_FORBIDDEN: "AI_SQL_FORBIDDEN",
  AI_SQL_INVALID: "AI_SQL_INVALID",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ErrorDefinition {
  code: ErrorCode;
  statusCode: number;
  message: string;
}

const BASE_ERROR_DEFINITIONS: Record<ErrorCode, Omit<ErrorDefinition, "code">> = {
  BAD_REQUEST: { statusCode: 400, message: "bad request" },
  VALIDATION_ERROR: { statusCode: 400, message: "validation error" },
  AUTH_UNAUTHORIZED: { statusCode: 401, message: "unauthorized" },
  AUTH_FORBIDDEN: { statusCode: 403, message: "forbidden" },
  AUTH_PASSWORD_INVALID: { statusCode: 400, message: "old password is invalid" },
  AUTH_CHALLENGE_INVALID: { statusCode: 401, message: "login challenge is invalid" },
  AUTH_CHALLENGE_EXPIRED: { statusCode: 401, message: "login challenge has expired" },
  AUTH_INVALID_ENCRYPTED_PASSWORD: { statusCode: 401, message: "invalid encrypted password" },
  TOKEN_SCOPE_FORBIDDEN: { statusCode: 403, message: "token scope forbidden" },
  TOKEN_NAME_REQUIRED: { statusCode: 400, message: "token name is required" },
  TOKEN_SCOPE_REQUIRED: { statusCode: 400, message: "at least one scope is required" },
  TOKEN_CREATE_FAILED: { statusCode: 500, message: "failed to create token" },
  TOKEN_NOT_FOUND: { statusCode: 404, message: "token not found" },
  TOKEN_UNAUTHORIZED: { statusCode: 401, message: "token unauthorized" },
  TOKEN_PROJECT_FORBIDDEN: { statusCode: 403, message: "token project forbidden" },
  TOKEN_OWNER_REQUIRED: { statusCode: 400, message: "token owner required" },
  TOKEN_RATE_LIMITED: { statusCode: 429, message: "token request rate limited" },
  PROJECT_CREATE_FORBIDDEN: { statusCode: 403, message: "create project forbidden" },
  PROJECT_NOT_FOUND: { statusCode: 404, message: "project not found" },
  PROJECT_NAME_REQUIRED: { statusCode: 400, message: "project name is required" },
  PROJECT_NO_REQUIRED: { statusCode: 400, message: "project number is required" },
  PROJECT_NO_CONFLICT: { statusCode: 409, message: "project number conflict" },
  PROJECT_UPDATE_FAILED: { statusCode: 500, message: "failed to update project" },
  PROJECT_ACCESS_DENIED: { statusCode: 403, message: "project access forbidden" },
  PROJECT_MEMBER_NOT_FOUND: { statusCode: 404, message: "project member not found" },
  PROJECT_MEMBER_EXISTS: { statusCode: 409, message: "project member already exists" },
  PROJECT_MEMBER_DELETE_FAILED: { statusCode: 500, message: "failed to remove project member" },
  PROJECT_MEMBER_ROLE_UNSUPPORTED: { statusCode: 400, message: "only promote-to-project-admin is supported" },
  PROJECT_OWNER_IMMUTABLE: { statusCode: 400, message: "project owner is immutable" },
  PROJECT_KEY_GENERATE_FAILED: { statusCode: 500, message: "failed to generate unique project key" },
  PROJECT_DISPLAY_CODE_CONFLICT: { statusCode: 409, message: "project display code conflict" },
  PROJECT_DISPLAY_CODE_GENERATE_FAILED: { statusCode: 500, message: "failed to generate unique displayCode" },
  PROJECT_CONFLICT: { statusCode: 409, message: "resource already exists" },
  PROJECT_INACTIVE: { statusCode: 400, message: "project is archived and read only" },
  PROJECT_MODULE_CREATE_FAILED: { statusCode: 500, message: "project module create failed" },
  PROJECT_MODULE_NOT_FOUND: { statusCode: 404, message: "project module not found" },
  PROJECT_MODULE_PARENT_INVALID: { statusCode: 400, message: "project module parent invalid" },
  PROJECT_MODULE_MEMBER_NOT_FOUND: { statusCode: 404, message: "project module member not found" },
  PROJECT_MODULE_MEMBER_EXISTS: { statusCode: 409, message: "project module member already exists" },
  PROJECT_ENVIRONMENT_CREATE_FAILED: { statusCode: 500, message: "project environment create failed" },
  PROJECT_ENVIRONMENT_NOT_FOUND: { statusCode: 404, message: "project environment not found" },
  PROJECT_VERSION_CREATE_FAILED: { statusCode: 500, message: "project version create failed" },
  PROJECT_VERSION_NOT_FOUND: { statusCode: 404, message: "project version not found" },
  USER_ALREADY_EXISTS: { statusCode: 409, message: "user already exists" },
  USER_NOT_FOUND: { statusCode: 404, message: "user not found" },
  USER_ACCESS_DENIED: { statusCode: 403, message: "get user forbidden" },
  SHARED_CONFIG_KEY_EXISTS: { statusCode: 409, message: "config key already exists" },
  SHARED_CONFIG_NOT_FOUND: { statusCode: 404, message: "shared config not found" },
  SHARED_CONFIG_UPDATE_FAILED: { statusCode: 500, message: "failed to update shared config" },
  ISSUE_NOT_FOUND: { statusCode: 404, message: "issue not found" },
  ISSUE_UPDATE_FAILED: { statusCode: 500, message: "failed to update issue" },
  ISSUE_ACTION_FAILED: { statusCode: 500, message: "issue action failed" },
  ISSUE_INVALID_TRANSITION: { statusCode: 400, message: "issue transition invalid" },
  ISSUE_EDIT_FORBIDDEN: { statusCode: 403, message: "issue edit forbidden" },
  ISSUE_ASSIGN_FORBIDDEN: { statusCode: 403, message: "issue assign forbidden" },
  ISSUE_CLAIM_FORBIDDEN: { statusCode: 403, message: "issue claim forbidden" },
  ISSUE_ALREADY_ASSIGNED: { statusCode: 409, message: "issue already assigned" },
  ISSUE_PARTICIPANT_FORBIDDEN: { statusCode: 403, message: "issue participant forbidden" },
  ISSUE_START_FORBIDDEN: { statusCode: 403, message: "issue start forbidden" },
  ISSUE_RESOLVE_FORBIDDEN: { statusCode: 403, message: "issue resolve forbidden" },
  ISSUE_VERIFY_FORBIDDEN: { statusCode: 403, message: "issue verify forbidden" },
  ISSUE_REOPEN_FORBIDDEN: { statusCode: 403, message: "issue reopen forbidden" },
  ISSUE_CLOSE_FORBIDDEN: { statusCode: 403, message: "issue close forbidden" },
  ISSUE_PARTICIPANT_EXISTS: { statusCode: 409, message: "issue participant exists" },
  ISSUE_PARTICIPANT_NOT_FOUND: { statusCode: 404, message: "issue participant not found" },
  ISSUE_PARTICIPANT_DELETE_FAILED: { statusCode: 500, message: "failed to delete participant" },
  ISSUE_ATTACHMENT_EXISTS: { statusCode: 409, message: "attachment already exists" },
  ISSUE_ATTACHMENT_NOT_FOUND: { statusCode: 404, message: "attachment not found" },
  ISSUE_ATTACHMENT_DELETE_FAILED: { statusCode: 500, message: "failed to delete attachment" },
  RD_STAGE_EXISTS: { statusCode: 409, message: "rd stage already exists" },
  RD_STAGE_NOT_FOUND: { statusCode: 404, message: "rd stage not found" },
  RD_STAGE_UPDATE_FAILED: { statusCode: 500, message: "failed to update rd stage" },
  RD_ITEM_NOT_FOUND: { statusCode: 404, message: "rd item not found" },
  RD_ITEM_UPDATE_FAILED: { statusCode: 500, message: "failed to update rd item" },
  RD_ITEM_DELETE_FAILED: { statusCode: 500, message: "failed to delete rd item" },
  RD_ITEM_VERSION_CONFLICT: { statusCode: 409, message: "rd item version conflict" },
  RD_ACTION_FAILED: { statusCode: 500, message: "rd action failed" },
  RD_INVALID_TRANSITION: { statusCode: 400, message: "rd transition invalid" },
  RD_STAGE_FORBIDDEN: { statusCode: 403, message: "rd stage forbidden" },
  RD_ACCEPT_FORBIDDEN: { statusCode: 403, message: "rd item accept forbidden" },
  RD_EDIT_FORBIDDEN: { statusCode: 403, message: "rd edit forbidden" },
  RD_DELETE_FORBIDDEN: { statusCode: 403, message: "rd delete forbidden" },
  RD_CLOSE_FORBIDDEN: { statusCode: 403, message: "rd close forbidden" },
  RD_PROGRESS_FORBIDDEN: { statusCode: 403, message: "rd progress forbidden" },
  RD_BLOCK_FORBIDDEN: { statusCode: 403, message: "rd block forbidden" },
  RD_ADVANCE_STAGE_FORBIDDEN: { statusCode: 403, message: "rd advance stage forbidden" },
  RD_ADVANCE_STAGE_INVALID_STATUS: { statusCode: 400, message: "rd item is not completed" },
  RD_ADVANCE_STAGE_INVALID_TARGET: { statusCode: 400, message: "rd target stage invalid" },
  RD_STAGE_PROJECT_MISMATCH: { statusCode: 400, message: "rd stage project mismatch" },
  RD_ADVANCE_STAGE_FAILED: { statusCode: 500, message: "failed to advance rd stage" },
  FEEDBACK_NOT_FOUND: { statusCode: 404, message: "feedback not found" },
  FEEDBACK_STATUS_UPDATE_FAILED: { statusCode: 500, message: "failed to update feedback status" },
  ANNOUNCEMENT_NOT_FOUND: { statusCode: 404, message: "announcement not found" },
  ANNOUNCEMENT_UPDATE_FAILED: { statusCode: 500, message: "failed to update announcement" },
  ANNOUNCEMENT_PUBLISH_FAILED: { statusCode: 500, message: "failed to publish announcement" },
  ANNOUNCEMENT_ARCHIVE_FAILED: { statusCode: 500, message: "failed to archive announcement" },
  DOCUMENT_NOT_FOUND: { statusCode: 404, message: "document not found" },
  DOCUMENT_SLUG_EXISTS: { statusCode: 409, message: "document slug already exists" },
  DOCUMENT_UPDATE_FAILED: { statusCode: 500, message: "failed to update document" },
  DOCUMENT_PUBLISH_FAILED: { statusCode: 500, message: "failed to publish document" },
  DOCUMENT_ARCHIVE_FAILED: { statusCode: 500, message: "failed to archive document" },
  RELEASE_NOT_FOUND: { statusCode: 404, message: "release not found" },
  RELEASE_UPDATE_FAILED: { statusCode: 500, message: "failed to update release" },
  RELEASE_PUBLISH_FAILED: { statusCode: 500, message: "failed to publish release" },
  RELEASE_ARCHIVE_FAILED: { statusCode: 500, message: "failed to archive release" },
  UPLOAD_NOT_FOUND: { statusCode: 404, message: "upload not found" },
  AI_SQL_FORBIDDEN: { statusCode: 400, message: "AI generated SQL contains forbidden keywords" },
  AI_SQL_INVALID: { statusCode: 400, message: "AI generated SQL is invalid" },
  NOT_FOUND: { statusCode: 404, message: "not found" },
  INTERNAL_ERROR: { statusCode: 500, message: "internal error" }
};

export const ERROR_DEFINITIONS: Record<ErrorCode, ErrorDefinition> = Object.entries(BASE_ERROR_DEFINITIONS).reduce(
  (acc, [code, value]) => {
    const typedCode = code as ErrorCode;
    acc[typedCode] = {
      code: typedCode,
      ...value
    };
    return acc;
  },
  {} as Record<ErrorCode, ErrorDefinition>
);

export function getErrorDefinition(code: string): ErrorDefinition | undefined {
  return ERROR_DEFINITIONS[code as ErrorCode];
}
