import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "fs";
import { basename, extname, join, resolve } from "path";

const packageRoot = resolve(__dirname, "..", "..");
const compiledSourceRoot = join(packageRoot, "lib", "src");
const pluginSketchRoot = join(
  packageRoot,
  "sketchplugin",
  "ngm-ai-handoff.sketchplugin",
  "Contents",
  "Sketch",
);
const resourcesRoot = join(packageRoot, "resources");

const commandEntries = [
  {
    commandId: "export-selected-artboard",
    fileName: "command-export-selected-artboard.js",
    handler: "onExportSelectedArtboard",
  },
  {
    commandId: "export-current-page",
    fileName: "command-export-current-page.js",
    handler: "onExportCurrentPage",
  },
  {
    commandId: "export-whole-document",
    fileName: "command-export-whole-document.js",
    handler: "onExportWholeDocument",
  },
  {
    commandId: "export-custom",
    fileName: "command-export-custom.js",
    handler: "onExportCustom",
  },
  {
    commandId: "open-settings",
    fileName: "command-open-settings.js",
    handler: "onOpenSettings",
  },
  {
    commandId: "diagnose-plugin-environment",
    fileName: "command-diagnose-plugin-environment.js",
    handler: "onDiagnosePluginEnvironment",
  },
  {
    commandId: "scan-current-page",
    fileName: "command-scan-current-page.js",
    handler: "onScanCurrentPage",
  },
];

function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true });
}

function collectFiles(dir: string): string[] {
  const files: string[] = [];

  function visit(current: string): void {
    if (!existsSync(current)) {
      return;
    }

    for (const entry of readdirSync(current)) {
      const filePath = join(current, entry);
      const stat = statSync(filePath);
      if (stat.isDirectory()) {
        visit(filePath);
      } else if (stat.isFile()) {
        files.push(filePath);
      }
    }
  }

  visit(dir);
  return files;
}

function cleanGeneratedRuntime(): void {
  ensureDir(pluginSketchRoot);
  for (const entry of readdirSync(pluginSketchRoot)) {
    if (entry === "manifest.json") {
      continue;
    }
    rmSync(join(pluginSketchRoot, entry), { recursive: true, force: true });
  }
}

function copyRuntime(): number {
  const files = collectFiles(compiledSourceRoot).filter((file) => extname(file) === ".js");
  for (const file of files) {
    const target = join(pluginSketchRoot, basename(file));
    writeFileSync(target, cleanRuntimeSource(readFileSync(file, "utf8")), "utf8");
  }
  writeFileSync(join(pluginSketchRoot, "main-bundle.js"), buildMainBundle(files), "utf8");
  writeFileSync(join(pluginSketchRoot, "canary.js"), buildCanaryScript(), "utf8");
  for (const entry of commandEntries) {
    writeFileSync(join(pluginSketchRoot, entry.fileName), buildCommandScript(entry.handler), "utf8");
  }
  updateManifestScripts();
  return files.length;
}

function cleanRuntimeSource(source: string): string {
  return source
    .replace(/^"use strict";\r?\nObject\.defineProperty\(exports, "__esModule", \{ value: true \}\);\r?\n/, "")
    .replace(/^"use strict";\r?\n/, "");
}

function moduleIdForFile(file: string): string {
  return basename(file, ".js");
}

function buildMainBundle(files: string[]): string {
  const sortedFiles = files.slice().sort((a, b) => moduleIdForFile(a).localeCompare(moduleIdForFile(b)));
  const modules = sortedFiles
    .map((file) => {
      const id = moduleIdForFile(file);
      const source = cleanRuntimeSource(readFileSync(file, "utf8"));
      return [
        `__ngmDefine(${JSON.stringify(id)}, function (require, module, exports) {`,
        source,
        "});",
      ].join("\n");
    })
    .join("\n\n");

  return `// Generated by scripts/build-plugin.ts. Sketch loads this file directly.
var __ngmHandlerRegistry = {};

(function () {
  var __ngmNativeRequire = typeof require === "function" ? require : null;
  var __ngmModules = {};
  var __ngmCache = {};

  function __ngmDefine(id, factory) {
    __ngmModules[id] = factory;
  }

  function __ngmNormalize(request) {
    var value = String(request || "");
    if (value.indexOf("./") === 0) {
      value = value.slice(2);
    }
    if (value.indexOf("../") === 0) {
      value = value.replace(/^\\.\\.\\//, "");
    }
    value = value.replace(/\\.js$/, "");
    var slash = value.lastIndexOf("/");
    return slash >= 0 ? value.slice(slash + 1) : value;
  }

  function __ngmRequire(request) {
    var id = __ngmNormalize(request);
    if (!__ngmModules[id]) {
      if (__ngmNativeRequire) {
        return __ngmNativeRequire(request);
      }
      throw new Error("Cannot require module: " + request);
    }
    if (__ngmCache[id]) {
      return __ngmCache[id].exports;
    }
    var module = { exports: {} };
    __ngmCache[id] = module;
    __ngmModules[id](function (nextRequest) {
      return __ngmRequire(nextRequest);
    }, module, module.exports);
    return module.exports;
  }

${modules}

  var __ngmHandlers = [
    "onExportSelectedArtboard",
    "onExportCurrentPage",
    "onExportWholeDocument",
    "onExportCustom",
    "onOpenSettings",
    "onDiagnosePluginEnvironment",
    "onScanCurrentPage"
  ];
  var __ngmMain = null;
  var __ngmBootstrapError = null;

  function __ngmShowBootstrapError() {
    var message = "NGM AI Handoff 插件启动失败";
    var detail = __ngmBootstrapError && __ngmBootstrapError.stack
      ? __ngmBootstrapError.stack
      : String(__ngmBootstrapError || "未知错误");
    try {
      var UI = __ngmNativeRequire ? __ngmNativeRequire("sketch/ui") : null;
      if (UI && UI.alert) {
        UI.alert(message, detail);
        return;
      }
    } catch (error) {
      // Ignore and try NSAlert below.
    }
    try {
      var alert = NSAlert.alloc().init();
      alert.setMessageText(message);
      alert.setInformativeText(detail);
      alert.addButtonWithTitle("确定");
      alert.runModal();
    } catch (error) {
      throw __ngmBootstrapError || error;
    }
  }

  try {
    __ngmMain = __ngmRequire("main");
  } catch (error) {
    __ngmBootstrapError = error;
  }

  for (var i = 0; i < __ngmHandlers.length; i += 1) {
    var name = __ngmHandlers[i];
    if (__ngmMain && typeof __ngmMain[name] === "function") {
      __ngmHandlerRegistry[name] = __ngmMain[name];
    } else {
      __ngmHandlerRegistry[name] = __ngmShowBootstrapError;
    }
  }
  if (typeof module !== "undefined" && module.exports) {
    module.exports = __ngmMain || {
      onExportSelectedArtboard: __ngmShowBootstrapError,
      onExportCurrentPage: __ngmShowBootstrapError,
      onExportWholeDocument: __ngmShowBootstrapError,
      onExportCustom: __ngmShowBootstrapError,
      onOpenSettings: __ngmShowBootstrapError,
      onDiagnosePluginEnvironment: __ngmShowBootstrapError,
      onScanCurrentPage: __ngmShowBootstrapError
    };
  }
}).call(this);

function onExportSelectedArtboard(context) {
  return __ngmHandlerRegistry.onExportSelectedArtboard(context);
}

function onExportCurrentPage(context) {
  return __ngmHandlerRegistry.onExportCurrentPage(context);
}

function onExportWholeDocument(context) {
  return __ngmHandlerRegistry.onExportWholeDocument(context);
}

function onExportCustom(context) {
  return __ngmHandlerRegistry.onExportCustom(context);
}

function onOpenSettings(context) {
  return __ngmHandlerRegistry.onOpenSettings(context);
}

function onDiagnosePluginEnvironment(context) {
  return __ngmHandlerRegistry.onDiagnosePluginEnvironment(context);
}

function onScanCurrentPage(context) {
  return __ngmHandlerRegistry.onScanCurrentPage(context);
}

if (typeof exports !== "undefined") {
  exports.onExportSelectedArtboard = onExportSelectedArtboard;
  exports.onExportCurrentPage = onExportCurrentPage;
  exports.onExportWholeDocument = onExportWholeDocument;
  exports.onExportCustom = onExportCustom;
  exports.onOpenSettings = onOpenSettings;
  exports.onDiagnosePluginEnvironment = onDiagnosePluginEnvironment;
  exports.onScanCurrentPage = onScanCurrentPage;
}
`;
}

function buildCanaryScript(): string {
  return `// Generated by scripts/build-plugin.ts. Minimal Sketch command canary.
function onCanary(context) {
  var message = "NGM AI Handoff canary 已执行";
  var detail = "Sketch 已成功加载 canary.js 并调用 onCanary。";
  try {
    var UI = require("sketch/ui");
    if (UI && UI.alert) {
      UI.alert(message, detail);
      return;
    }
  } catch (error) {
    // Fall back to NSAlert below.
  }
  var alert = NSAlert.alloc().init();
  alert.setMessageText(message);
  alert.setInformativeText(detail);
  alert.addButtonWithTitle("确定");
  alert.runModal();
}

if (typeof exports !== "undefined") {
  exports.onCanary = onCanary;
}
`;
}

function buildCommandScript(handlerName: string): string {
  return `// Generated by scripts/build-plugin.ts. Thin Sketch command entry.
function ${handlerName}(context) {
  try {
    var plugin = require("./main-bundle");
    if (!plugin || typeof plugin.${handlerName} !== "function") {
      throw new Error("业务入口未导出 ${handlerName}");
    }
    return plugin.${handlerName}(context);
  } catch (error) {
    var title = "NGM AI Handoff 插件执行失败";
    var detail = error && error.stack ? error.stack : String(error || "未知错误");
    try {
      var UI = require("sketch/ui");
      if (UI && UI.alert) {
        UI.alert(title, detail);
        return null;
      }
    } catch (innerError) {
      // Fall back to NSAlert below.
    }
    var alert = NSAlert.alloc().init();
    alert.setMessageText(title);
    alert.setInformativeText(detail);
    alert.addButtonWithTitle("确定");
    alert.runModal();
    return null;
  }
}

if (typeof exports !== "undefined") {
  exports.${handlerName} = ${handlerName};
}
`;
}

function updateManifestScripts(): void {
  const manifestPath = join(pluginSketchRoot, "manifest.json");
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const byCommandId = commandEntries.reduce<Record<string, (typeof commandEntries)[number]>>((result, entry) => {
    result[entry.commandId] = entry;
    return result;
  }, {});

  manifest.commands = (manifest.commands || []).map((command: any) => {
    const entry = byCommandId[command.identifier];
    if (!entry) {
      return command;
    }
    return {
      ...command,
      script: entry.fileName,
      handler: entry.handler,
    };
  });

  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
}

function copyResources(): number {
  const files = collectFiles(resourcesRoot);
  for (const file of files) {
    const rel = file.slice(resourcesRoot.length + 1);
    const target = join(pluginSketchRoot, "resources", rel);
    ensureDir(resolve(target, ".."));
    copyFileSync(file, target);
  }
  return files.length;
}

if (!existsSync(compiledSourceRoot)) {
  throw new Error(`Compiled plugin source does not exist: ${compiledSourceRoot}`);
}

cleanGeneratedRuntime();
const runtimeCount = copyRuntime();
const resourceCount = copyResources();

console.log(`Built Sketch plugin runtime: ${runtimeCount} file(s)`);
console.log(`Copied Sketch plugin resources: ${resourceCount} file(s)`);
console.log(`Plugin output: ${pluginSketchRoot}`);
