import type { ToolCatalogEntry } from "../types";

export const frontendStandardTools: ToolCatalogEntry[] = [
  {
    name: "ngm_git_validate_branch_name",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Validate a branch name against configured frontend workflow patterns.",
  },
  {
    name: "ngm_git_validate_commit_message",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Validate a commit message against configured frontend commit rules.",
  },
  {
    name: "ngm_git_generate_commit_message",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Generate a conventional frontend commit message.",
  },
  {
    name: "ngm_git_generate_review_summary",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Generate a compact review summary from changed files and Git context.",
  },
  {
    name: "ngm_standard_get",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Read frontend standard config or defaults.",
  },
  {
    name: "ngm_standard_init",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "write",
    description: "Preview or create .ng-manager/frontend-standard.json.",
  },
  {
    name: "ngm_standard_validate_project",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Run lightweight frontend project standard checks.",
  },
  {
    name: "ngm_test_detect_missing_specs",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Detect suggested missing frontend specs.",
  },
  {
    name: "ngm_test_generate_spec_plan",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Generate a lightweight frontend spec plan.",
  },
  {
    name: "ngm_test_validate_naming",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Validate frontend test naming conventions.",
  },
  {
    name: "ngm_angular_validate_structure",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Validate Angular directory structure.",
  },
  {
    name: "ngm_angular_validate_component_naming",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Validate Angular component naming.",
  },
  {
    name: "ngm_angular_validate_component_boundary",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Detect large components, obvious any usage, and hardcoded API URLs.",
  },
  {
    name: "ngm_review_scan_changed_files",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Read changed files for review workflows.",
  },
  {
    name: "ngm_review_generate_checklist",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Generate frontend review checklist.",
  },
  {
    name: "ngm_review_detect_risks",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Detect lightweight review risks in changed files.",
  },
  {
    name: "ngm_review_generate_report",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "write",
    description: "Preview or write frontend review report under .ng-manager/frontend-tasks/{taskId}/review-report.md.",
  },
  {
    name: "ngm_workflow_create_frontend_task",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or create frontend workflow task metadata.",
  },
  {
    name: "ngm_workflow_generate_dev_plan",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or write frontend workflow dev plan.",
  },
  {
    name: "ngm_workflow_advance_status",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or advance a frontend workflow task status through controlled transitions.",
  },
  {
    name: "ngm_workflow_validate_before_write",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or persist frontend project checks before AI writes source changes.",
  },
  {
    name: "ngm_workflow_validate_before_commit",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or persist frontend standard/test/review/Git checks before commit.",
  },
  {
    name: "ngm_workflow_generate_delivery_report",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or write frontend workflow delivery report.",
  },
];

