import type { ToolCatalogEntry } from "../types";

export const frontendStandardTools: ToolCatalogEntry[] = [
  {
    name: "ngm.git.validateBranchName",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Validate a branch name against configured frontend workflow patterns.",
  },
  {
    name: "ngm.git.validateCommitMessage",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Validate a commit message against configured frontend commit rules.",
  },
  {
    name: "ngm.git.generateCommitMessage",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Generate a conventional frontend commit message.",
  },
  {
    name: "ngm.git.generateReviewSummary",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Generate a compact review summary from changed files and Git context.",
  },
  {
    name: "ngm.standard.get",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Read frontend standard config or defaults.",
  },
  {
    name: "ngm.standard.init",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "write",
    description: "Preview or create .ng-manager/frontend-standard.json.",
  },
  {
    name: "ngm.standard.validateProject",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Run lightweight frontend project standard checks.",
  },
  {
    name: "ngm.test.detectMissingSpecs",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Detect suggested missing frontend specs.",
  },
  {
    name: "ngm.test.generateSpecPlan",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Generate a lightweight frontend spec plan.",
  },
  {
    name: "ngm.test.validateNaming",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Validate frontend test naming conventions.",
  },
  {
    name: "ngm.angular.validateStructure",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Validate Angular directory structure.",
  },
  {
    name: "ngm.angular.validateComponentNaming",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Validate Angular component naming.",
  },
  {
    name: "ngm.angular.validateComponentBoundary",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Detect large components, obvious any usage, and hardcoded API URLs.",
  },
  {
    name: "ngm.review.scanChangedFiles",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Read changed files for review workflows.",
  },
  {
    name: "ngm.review.generateChecklist",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Generate frontend review checklist.",
  },
  {
    name: "ngm.review.detectRisks",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Detect lightweight review risks in changed files.",
  },
  {
    name: "ngm.review.generateReport",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "write",
    description: "Preview or write frontend review report under .ng-manager/frontend-tasks/{taskId}/review-report.md.",
  },
  {
    name: "ngm.workflow.createFrontendTask",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or create frontend workflow task metadata.",
  },
  {
    name: "ngm.workflow.generateDevPlan",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or write frontend workflow dev plan.",
  },
  {
    name: "ngm.workflow.advanceStatus",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or advance a frontend workflow task status through controlled transitions.",
  },
  {
    name: "ngm.workflow.validateBeforeWrite",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or persist frontend project checks before AI writes source changes.",
  },
  {
    name: "ngm.workflow.validateBeforeCommit",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or persist frontend standard/test/review/Git checks before commit.",
  },
  {
    name: "ngm.workflow.generateDeliveryReport",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or write frontend workflow delivery report.",
  },
];

