import type { ToolCatalogEntry } from "../types";

export const hubV2ApiTools: ToolCatalogEntry[] = [
  {
    name: "hub_v2_projects_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List configured Hub V2 projects.",
  },
  {
    name: "hub_v2_projects_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one configured Hub V2 project.",
  },
  {
    name: "hub_v2_project_members_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 project members.",
  },
  {
    name: "hub_v2_issues_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 issues.",
  },
  {
    name: "hub_v2_issues_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one Hub V2 issue.",
  },
  {
    name: "hub_v2_issues_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_comment",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or add a Hub V2 issue comment with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_assign",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or assign a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_update",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or update a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_upload_markdown_image",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or upload a Markdown image for Hub V2 write workflows.",
  },
  {
    name: "hub_v2_rd_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 RD items.",
  },
  {
    name: "hub_v2_rd_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one Hub V2 RD item.",
  },
  {
    name: "hub_v2_rd_stage_tasks_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List stage tasks for one Hub V2 RD item.",
  },
  {
    name: "hub_v2_rd_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create a Hub V2 RD item with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_advance_stage",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or advance a Hub V2 RD stage with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_stage_tasks_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create Hub V2 RD stage tasks with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_update_progress",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or update Hub V2 RD progress with explicit confirmation.",
  },
];
