import type { ToolCatalogEntry } from "../types";

export const projectTools: ToolCatalogEntry[] = [
  {
    name: "ngm_project_list",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List registered ng-manager projects by projectId; prefer before shell discovery because it uses the project registry and does not scan arbitrary roots.",
  },
  {
    name: "ngm_project_managed_list",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List projects managed by ng-manager.",
  },
  {
    name: "ngm_project_find",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Find ng-manager local projects by name, path, framework, or package manager.",
  },
  {
    name: "ngm_project_get",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get one ng-manager project by projectId or projectPath.",
  },
  {
    name: "ngm_project_get_scripts",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get package scripts and runtime hints for one ng-manager project.",
  },
  {
    name: "ngm_project_read_package_json",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Read package.json metadata for one registered ng-manager local project.",
  },
  {
    name: "ngm_project_run_script",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "execute",
    description: "Preview or run an existing package.json script for a registered projectId through the local ng-manager server runtime; preferred over direct shell so task state, logs, and audit stay unified.",
  },
  {
    name: "ngm_project_stop",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "execute",
    description: "Preview or stop a ng-manager managed task by taskId or projectId through the local server runtime; preferred over killing PIDs and audit logged when confirmed.",
  },
  {
    name: "ngm_file_write",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "write",
    description: "Preview or write a text file inside a registered project using projectId and safe relativePath only; rejects absolute paths/traversal and audit logs confirmed writes.",
  },
  {
    name: "ngm_project_list_tasks",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List ng-manager managed project tasks from the shared local server runtime state.",
  },
  {
    name: "ngm_project_task_status",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Read structured runtime status for one ng-manager managed task.",
  },
  {
    name: "ngm_project_task_logs",
    skill: "ngm-project",
    capability: "logs",
    riskLevel: "read",
    description: "Read a limited, redacted log tail for one ng-manager managed task or run.",
  },
  {
    name: "ngm_project_port_check",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Check whether one local host/port is listening without shell execution or range scanning.",
  },
  {
    name: "ngm_project_health_check",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Perform a short local HTTP health check by URL or managed task/project runtime URL.",
  },
  {
    name: "ngm_task_list",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List registered task views for a project, or active tasks when projectId is omitted.",
  },
  {
    name: "ngm_task_get_status",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get the runtime status for a registered task.",
  },
  {
    name: "ngm_log_tail",
    skill: "ngm-project",
    capability: "logs",
    riskLevel: "read",
    description: "Read recent task logs by runId or taskId.",
  },
];

