// This file is generated by apps/hub-v2/scripts/generate-upload-policies.mjs.
// Edit apps/hub-v2/shared/upload-policies.schema.json instead.

import type { UploadPolicy } from './upload-policy';

export const GENERATED_UPLOAD_POLICIES = {
  "markdownImage": {
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg"
    ],
    "invalidTypeMessage": "仅支持图片文件",
    "sizeLimitMessage": "图片大小不能超过 10MB"
  },
  "commentImage": {
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg"
    ],
    "invalidTypeMessage": "仅支持图片文件",
    "sizeLimitMessage": "评论图片不能超过 10MB"
  },
  "profileAvatar": {
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg"
    ],
    "invalidTypeMessage": "仅支持图片文件",
    "sizeLimitMessage": "头像图片不能超过 10MB"
  },
  "projectAvatar": {
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg"
    ],
    "invalidTypeMessage": "仅支持图片文件",
    "sizeLimitMessage": "图片大小不能超过 10MB"
  },
  "issueAttachment": {
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/",
      "video/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg",
      ".mp4",
      ".mov",
      ".webm",
      ".mkv",
      ".avi",
      ".m4v",
      ".flv",
      ".wmv"
    ],
    "invalidTypeMessage": "仅支持上传图片或视频文件",
    "sizeLimitMessage": "单个文件最大 10MB"
  },
  "reimbursementAttachment": {
    "maxSizeBytes": 10485760,
    "allowedMimeTypes": [
      "image/jpeg",
      "image/png",
      "image/jpg",
      "application/pdf"
    ],
    "allowedExtensions": [
      ".jpg",
      ".jpeg",
      ".png",
      ".pdf"
    ],
    "invalidTypeMessage": "仅支持上传图片或 PDF 文件",
    "sizeLimitMessage": "单个文件最大 10MB"
  },
  "taskSheetAttachment": {
    "maxSizeBytes": 10485760,
    "allowedMimeTypes": [
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/pdf",
      "image/jpeg",
      "image/png",
      "image/jpg"
    ],
    "allowedExtensions": [
      ".doc",
      ".docx",
      ".pdf",
      ".jpg",
      ".jpeg",
      ".png"
    ],
    "invalidTypeMessage": "仅支持 Word / PDF / JPG / PNG 文件",
    "sizeLimitMessage": "单个文件最大 10MB"
  },
  "taskSheetWordImport": {
    "maxSizeBytes": 10485760,
    "allowedMimeTypes": [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ],
    "allowedExtensions": [
      ".docx"
    ],
    "invalidTypeMessage": "仅支持 .docx 任务单文件",
    "sizeLimitMessage": "单个文件最大 10MB"
  },
  "skillPackage": {
    "maxSizeBytes": 10485760,
    "allowedMimeTypes": [
      "application/zip",
      "application/x-zip-compressed",
      "application/octet-stream"
    ],
    "allowedExtensions": [
      ".zip"
    ],
    "invalidTypeMessage": "仅支持上传 zip 格式 skill 包",
    "sizeLimitMessage": "skill 包大小不能超过 10MB"
  },
  "mobileAppPackage": {
    "maxSizeBytes": 209715200,
    "allowedMimeTypes": [
      "application/vnd.android.package-archive",
      "application/octet-stream",
      "application/zip",
      "application/x-itunes-ipa"
    ],
    "allowedExtensions": [
      ".apk",
      ".ipa"
    ],
    "invalidTypeMessage": "仅支持上传 apk 或 ipa 安装包",
    "sizeLimitMessage": "安装包大小不能超过 200MB"
  }
} as const satisfies Record<string, UploadPolicy>;

export const SERVER_UPLOAD_POLICY_RULES = [
  {
    "target": "profileAvatar",
    "bucket": "avatars"
  },
  {
    "target": "projectAvatar",
    "bucket": "project-avatars"
  },
  {
    "target": "commentImage",
    "category": "comment"
  },
  {
    "target": "markdownImage",
    "categoryPrefix": "markdown"
  },
  {
    "target": "issueAttachment",
    "bucket": "issues",
    "category": "attachment"
  },
  {
    "target": "reimbursementAttachment",
    "bucket": "reimbursements",
    "category": "attachment"
  },
  {
    "target": "taskSheetAttachment",
    "bucket": "task-sheets",
    "category": "attachment"
  },
  {
    "target": "taskSheetWordImport",
    "bucket": "task-sheets",
    "category": "word_import"
  },
  {
    "target": "skillPackage",
    "bucket": "skills",
    "category": "package"
  },
  {
    "target": "mobileAppPackage",
    "bucket": "mobile-apps",
    "category": "package"
  }
] as const;

export const ALLOWED_UPLOAD_BUCKETS = [
  "avatars",
  "documents",
  "issues",
  "misc",
  "mobile-apps",
  "personal-todos",
  "project-avatars",
  "rd",
  "reimbursements",
  "skills",
  "task-sheets",
  "temp"
] as const;
