import type { ToolRiskLevel } from "../policy/tool-policy";

export type ToolCatalogEntry = {
  name: string;
  skill: string;
  capability: string;
  riskLevel: ToolRiskLevel;
  description: string;
};

export type CapabilityCatalogEntry = {
  id: string;
  label: string;
  skills: string[];
  tools: string[];
  notes?: string[];
};

export const toolCatalog: ToolCatalogEntry[] = [
  {
    name: "ngm.capabilities",
    skill: "ngm-router",
    capability: "discovery",
    riskLevel: "read",
    description: "List ng-manager MCP capability groups, skills, and tool coverage.",
  },
  {
    name: "ngm.routeTask",
    skill: "ngm-router",
    capability: "routing",
    riskLevel: "read",
    description: "Route a user request to Hub V2 or NGM local skills and read-only MCP tools.",
  },
  {
    name: "ngm.workspace.summary",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Summarize the local ng-manager workspace and major app/package areas.",
  },
  {
    name: "ngm.workspace.listPackages",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "List local workspace package metadata from known ng-manager package roots.",
  },
  {
    name: "ngm.workspace.getPackage",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Get package.json metadata for one local workspace package or app.",
  },
  {
    name: "ngm.workspace.mcpTools",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "List ng-manager MCP tools with capability and skill mapping.",
  },
  {
    name: "ngm.workspace.capabilityMap",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Map ng-manager workspace areas to local capability domains.",
  },
  {
    name: "ngm.project.list",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List projects managed by ng-manager.",
  },
  {
    name: "ngm.project.find",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Find ng-manager local projects by name, path, framework, or package manager.",
  },
  {
    name: "ngm.project.get",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get one ng-manager project by projectId or projectPath.",
  },
  {
    name: "ngm.project.getScripts",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get package scripts and runtime hints for one ng-manager project.",
  },
  {
    name: "ngm.project.readPackageJson",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Read package.json metadata for one registered ng-manager local project.",
  },
  {
    name: "ngm_project_run_script",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "execute",
    description: "Preview or run an existing package.json script through ng-manager task services with explicit confirmation.",
  },
  {
    name: "ngm_project_stop",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "execute",
    description: "Preview or stop one ng-manager managed task process with explicit confirmation.",
  },
  {
    name: "ngm_project_list_tasks",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List ng-manager managed project tasks from the shared local server runtime state.",
  },
  {
    name: "ngm_project_task_status",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Read structured runtime status for one ng-manager managed task.",
  },
  {
    name: "ngm_project_task_logs",
    skill: "ngm-project",
    capability: "logs",
    riskLevel: "read",
    description: "Read a limited, redacted log tail for one ng-manager managed task or run.",
  },
  {
    name: "ngm_project_port_check",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Check whether one local host/port is listening without shell execution or range scanning.",
  },
  {
    name: "ngm_project_health_check",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Perform a short local HTTP health check by URL or managed task/project runtime URL.",
  },
  {
    name: "ngm.runtime.current",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "read",
    description: "Read current Node version manager information.",
  },
  {
    name: "ngm.runtime.list",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "read",
    description: "List Node runtimes known to ng-manager.",
  },
  {
    name: "ngm.runtime.resolveForProject",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "read",
    description: "Resolve the Node runtime ng-manager would use for a project.",
  },
  {
    name: "ngm.runtime.detectRequirement",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "read",
    description: "Detect project Node version requirements from package metadata.",
  },
  {
    name: "ngm_runtime_set_for_project",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "write",
    description: "Preview or set a managed project's Node runtime binding with explicit confirmation.",
  },
  {
    name: "ngm.nginx.status",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Read local Nginx binding and process status.",
  },
  {
    name: "ngm.nginx.servers.list",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "List local Nginx server blocks.",
  },
  {
    name: "ngm.nginx.server.get",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Get one local Nginx server block.",
  },
  {
    name: "ngm.nginx.upstreams.list",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "List local Nginx upstream definitions.",
  },
  {
    name: "ngm.nginx.config.validate",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Validate current or supplied local Nginx config without reload.",
  },
  {
    name: "ngm.nginx.config.getMain",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Read local Nginx main config metadata and content.",
  },
  {
    name: "ngm.nginx.logs.tail",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Read recent local Nginx access or error log lines.",
  },
  {
    name: "ngm_nginx_reload",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "execute",
    description: "Validate and preview or reload the ng-manager managed local Nginx instance with explicit confirmation.",
  },
  {
    name: "ngm_nginx_proxy_save",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "write",
    description: "Preview or save a ng-manager managed Nginx proxy server block with explicit confirmation.",
  },
  {
    name: "ngm.proxy.list",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Compatibility tool for current ng-manager Nginx/proxy bindings.",
  },
  {
    name: "ngm.proxy.validate",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Compatibility tool for validating Nginx/proxy config.",
  },
  {
    name: "ngm.task.list",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List registered task views for a project, or active tasks when projectId is omitted.",
  },
  {
    name: "ngm.task.getStatus",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get the runtime status for a registered task.",
  },
  {
    name: "ngm.log.tail",
    skill: "ngm-project",
    capability: "logs",
    riskLevel: "read",
    description: "Read recent task logs by runId or taskId.",
  },
  {
    name: "ngm.log.search",
    skill: "ngm-workspace",
    capability: "logs",
    riskLevel: "read",
    description: "Search recent ng-manager system logs by keyword.",
  },
  {
    name: "ngm.git.status",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Read Git working tree status for a project when the core Git service is available.",
  },
  {
    name: "ngm.git.diff",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Read Git diff for a project when the core Git service is available.",
  },
  {
    name: "ngm.git.validateBranchName",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Validate a branch name against configured frontend workflow patterns.",
  },
  {
    name: "ngm.git.validateCommitMessage",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Validate a commit message against configured frontend commit rules.",
  },
  {
    name: "ngm.git.generateCommitMessage",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Generate a conventional frontend commit message.",
  },
  {
    name: "ngm.git.generateReviewSummary",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Generate a compact review summary from changed files and Git context.",
  },
  {
    name: "ngm.standard.get",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Read frontend standard config or defaults.",
  },
  {
    name: "ngm.standard.init",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "write",
    description: "Preview or create .ng-manager/frontend-standard.json.",
  },
  {
    name: "ngm.standard.validateProject",
    skill: "ngm-frontend-standard",
    capability: "frontend-standard",
    riskLevel: "read",
    description: "Run lightweight frontend project standard checks.",
  },
  {
    name: "ngm.test.detectMissingSpecs",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Detect suggested missing frontend specs.",
  },
  {
    name: "ngm.test.generateSpecPlan",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Generate a lightweight frontend spec plan.",
  },
  {
    name: "ngm.test.validateNaming",
    skill: "ngm-frontend-standard",
    capability: "frontend-testing",
    riskLevel: "read",
    description: "Validate frontend test naming conventions.",
  },
  {
    name: "ngm.angular.validateStructure",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Validate Angular directory structure.",
  },
  {
    name: "ngm.angular.validateComponentNaming",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Validate Angular component naming.",
  },
  {
    name: "ngm.angular.validateComponentBoundary",
    skill: "ngm-frontend-standard",
    capability: "frontend-angular",
    riskLevel: "read",
    description: "Detect large components, obvious any usage, and hardcoded API URLs.",
  },
  {
    name: "ngm.review.scanChangedFiles",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Read changed files for review workflows.",
  },
  {
    name: "ngm.review.generateChecklist",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Generate frontend review checklist.",
  },
  {
    name: "ngm.review.detectRisks",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "read",
    description: "Detect lightweight review risks in changed files.",
  },
  {
    name: "ngm.review.generateReport",
    skill: "ngm-frontend-standard",
    capability: "frontend-review",
    riskLevel: "write",
    description: "Preview or write frontend review report under .ng-manager/reports.",
  },
  {
    name: "ngm.workflow.createFrontendTask",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or create frontend workflow task metadata.",
  },
  {
    name: "ngm.workflow.generateDevPlan",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or write frontend workflow dev plan.",
  },
  {
    name: "ngm.workflow.validateBeforeWrite",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "read",
    description: "Validate frontend project before AI writes source changes.",
  },
  {
    name: "ngm.workflow.validateBeforeCommit",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "read",
    description: "Validate frontend project and changed files before commit.",
  },
  {
    name: "ngm.workflow.generateDeliveryReport",
    skill: "ngm-frontend-standard",
    capability: "frontend-workflow",
    riskLevel: "write",
    description: "Preview or write frontend workflow delivery report.",
  },
  {
    name: "hub_v2_projects_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List configured Hub V2 projects.",
  },
  {
    name: "hub_v2_projects_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one configured Hub V2 project.",
  },
  {
    name: "hub_v2_project_members_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 project members.",
  },
  {
    name: "hub_v2_docs_list",
    skill: "hub-v2-docs",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 project documents.",
  },
  {
    name: "hub_v2_docs_get",
    skill: "hub-v2-docs",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Read a Hub V2 project document by id.",
  },
  {
    name: "hub_v2_docs_get_by_slug",
    skill: "hub-v2-docs",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Read a Hub V2 project document by slug.",
  },
  {
    name: "hub_v2_issues_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 issues.",
  },
  {
    name: "hub_v2_issues_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one Hub V2 issue.",
  },
  {
    name: "hub_v2_issues_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_comment",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or add a Hub V2 issue comment with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_assign",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or assign a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_update",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or update a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_upload_markdown_image",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or upload a Markdown image for Hub V2 write workflows.",
  },
  {
    name: "hub_v2_rd_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 RD items.",
  },
  {
    name: "hub_v2_rd_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one Hub V2 RD item.",
  },
  {
    name: "hub_v2_rd_stage_tasks_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List stage tasks for one Hub V2 RD item.",
  },
  {
    name: "hub_v2_rd_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create a Hub V2 RD item with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_advance_stage",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or advance a Hub V2 RD stage with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_stage_tasks_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create Hub V2 RD stage tasks with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_update_progress",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or update Hub V2 RD progress with explicit confirmation.",
  },
];

export const capabilityCatalog: CapabilityCatalogEntry[] = [
  {
    id: "routing",
    label: "Skill routing and MCP capability discovery",
    skills: ["ngm-router"],
    tools: ["ngm.capabilities", "ngm.routeTask"],
  },
  {
    id: "workspace",
    label: "Local ng-manager workspace, monorepo, package metadata, MCP tools, API debugging, design handoff, and CodeGraph availability",
    skills: ["ngm-workspace"],
    tools: [
      "ngm.workspace.summary",
      "ngm.workspace.listPackages",
      "ngm.workspace.getPackage",
      "ngm.workspace.mcpTools",
      "ngm.workspace.capabilityMap",
      "ngm.git.status",
      "ngm.git.diff",
      "ngm.log.search",
    ],
    notes: ["CodeGraph DB is not exposed directly by this MCP server in the current read-only phase."],
  },
  {
    id: "frontend-standard",
    label: "Enterprise frontend standard, Angular structure checks, test guidance, code review reports, and workflow task files",
    skills: ["ngm-frontend-standard"],
    tools: [
      "ngm.standard.get",
      "ngm.standard.init",
      "ngm.standard.validateProject",
      "ngm.git.validateBranchName",
      "ngm.git.validateCommitMessage",
      "ngm.git.generateCommitMessage",
      "ngm.git.generateReviewSummary",
      "ngm.test.detectMissingSpecs",
      "ngm.test.generateSpecPlan",
      "ngm.test.validateNaming",
      "ngm.angular.validateStructure",
      "ngm.angular.validateComponentNaming",
      "ngm.angular.validateComponentBoundary",
      "ngm.review.scanChangedFiles",
      "ngm.review.generateChecklist",
      "ngm.review.detectRisks",
      "ngm.review.generateReport",
      "ngm.workflow.createFrontendTask",
      "ngm.workflow.generateDevPlan",
      "ngm.workflow.validateBeforeWrite",
      "ngm.workflow.validateBeforeCommit",
      "ngm.workflow.generateDeliveryReport",
    ],
    notes: ["Write tools only write project-local .ng-manager files and require confirm=true plus NGM_MCP_ALLOW_WRITE=true."],
  },
  {
    id: "project",
    label: "Local project entries, package.json scripts, task views, process status, and logs",
    skills: ["ngm-project"],
    tools: [
      "ngm.project.list",
      "ngm.project.find",
      "ngm.project.get",
      "ngm.project.getScripts",
      "ngm.project.readPackageJson",
      "ngm_project_run_script",
      "ngm_project_stop",
      "ngm_project_list_tasks",
      "ngm_project_task_status",
      "ngm_project_task_logs",
      "ngm_project_port_check",
      "ngm_project_health_check",
      "ngm.task.list",
      "ngm.task.getStatus",
      "ngm.log.tail",
    ],
  },
  {
    id: "runtime",
    label: "Node runtime, Node version manager, and project runtime resolution",
    skills: ["ngm-runtime"],
    tools: [
      "ngm.runtime.current",
      "ngm.runtime.list",
      "ngm.runtime.resolveForProject",
      "ngm.runtime.detectRequirement",
      "ngm_runtime_set_for_project",
    ],
  },
  {
    id: "nginx",
    label: "Local Nginx status, server blocks, upstreams, config validation, and logs",
    skills: ["ngm-nginx"],
    tools: [
      "ngm.nginx.status",
      "ngm.nginx.servers.list",
      "ngm.nginx.server.get",
      "ngm.nginx.upstreams.list",
      "ngm.nginx.config.validate",
      "ngm.nginx.config.getMain",
      "ngm.nginx.logs.tail",
      "ngm_nginx_reload",
      "ngm_nginx_proxy_save",
      "ngm.proxy.list",
      "ngm.proxy.validate",
    ],
  },
  {
    id: "hub-v2",
    label: "Hub V2 collaboration data: issues, RD workflows, documents, members, and uploads",
    skills: ["hub-v2-api", "hub-v2-docs"],
    tools: [
      "hub_v2_projects_list",
      "hub_v2_projects_get",
      "hub_v2_project_members_list",
      "hub_v2_docs_list",
      "hub_v2_docs_get",
      "hub_v2_docs_get_by_slug",
      "hub_v2_issues_list",
      "hub_v2_issues_get",
      "hub_v2_issues_create",
      "hub_v2_issues_comment",
      "hub_v2_issues_assign",
      "hub_v2_issues_update",
      "hub_v2_upload_markdown_image",
      "hub_v2_rd_list",
      "hub_v2_rd_get",
      "hub_v2_rd_stage_tasks_list",
      "hub_v2_rd_create",
      "hub_v2_rd_advance_stage",
      "hub_v2_rd_stage_tasks_create",
      "hub_v2_rd_update_progress",
    ],
  },
];

export const blockedLocalActions = [
  "run package scripts without confirm=true and NGM_MCP_ALLOW_EXECUTE=true",
  "stop local project processes without confirm=true and NGM_MCP_ALLOW_EXECUTE=true",
  "restart local project processes",
  "install, uninstall, or switch Node versions",
  "change project runtime binding without confirm=true and NGM_MCP_ALLOW_WRITE=true",
  "start or stop Nginx",
  "reload Nginx without config validation, confirm=true, and NGM_MCP_ALLOW_EXECUTE=true",
  "write Nginx proxy rules without confirm=true and NGM_MCP_ALLOW_WRITE=true",
  "execute arbitrary shell commands",
  "kill arbitrary PIDs",
  "write arbitrary file paths",
  "write frontend standard, review, or workflow files outside project-local .ng-manager/**",
];
