import type { ToolRiskLevel } from "../policy/tool-policy";

export type ToolCatalogEntry = {
  name: string;
  skill: string;
  capability: string;
  riskLevel: ToolRiskLevel;
  description: string;
};

export type CapabilityCatalogEntry = {
  id: string;
  label: string;
  skills: string[];
  tools: string[];
  notes?: string[];
};

export const toolCatalog: ToolCatalogEntry[] = [
  {
    name: "ngm.capabilities",
    skill: "ngm-router",
    capability: "discovery",
    riskLevel: "read",
    description: "List ng-manager MCP capability groups, skills, and tool coverage.",
  },
  {
    name: "ngm.routeTask",
    skill: "ngm-router",
    capability: "routing",
    riskLevel: "read",
    description: "Route a user request to Hub V2 or NGM local skills and read-only MCP tools.",
  },
  {
    name: "ngm.workspace.summary",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Summarize the local ng-manager workspace and major app/package areas.",
  },
  {
    name: "ngm.workspace.listPackages",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "List local workspace package metadata from known ng-manager package roots.",
  },
  {
    name: "ngm.workspace.getPackage",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Get package.json metadata for one local workspace package or app.",
  },
  {
    name: "ngm.workspace.mcpTools",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "List ng-manager MCP tools with capability and skill mapping.",
  },
  {
    name: "ngm.workspace.capabilityMap",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Map ng-manager workspace areas to local capability domains.",
  },
  {
    name: "ngm.project.list",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List projects managed by ng-manager.",
  },
  {
    name: "ngm.project.find",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Find ng-manager local projects by name, path, framework, or package manager.",
  },
  {
    name: "ngm.project.get",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get one ng-manager project by projectId or projectPath.",
  },
  {
    name: "ngm.project.getScripts",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get package scripts and runtime hints for one ng-manager project.",
  },
  {
    name: "ngm.project.readPackageJson",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Read package.json metadata for one registered ng-manager local project.",
  },
  {
    name: "ngm.runtime.current",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "read",
    description: "Read current Node version manager information.",
  },
  {
    name: "ngm.runtime.list",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "read",
    description: "List Node runtimes known to ng-manager.",
  },
  {
    name: "ngm.runtime.resolveForProject",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "read",
    description: "Resolve the Node runtime ng-manager would use for a project.",
  },
  {
    name: "ngm.runtime.detectRequirement",
    skill: "ngm-runtime",
    capability: "runtime",
    riskLevel: "read",
    description: "Detect project Node version requirements from package metadata.",
  },
  {
    name: "ngm.nginx.status",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Read local Nginx binding and process status.",
  },
  {
    name: "ngm.nginx.servers.list",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "List local Nginx server blocks.",
  },
  {
    name: "ngm.nginx.server.get",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Get one local Nginx server block.",
  },
  {
    name: "ngm.nginx.upstreams.list",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "List local Nginx upstream definitions.",
  },
  {
    name: "ngm.nginx.config.validate",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Validate current or supplied local Nginx config without reload.",
  },
  {
    name: "ngm.nginx.config.getMain",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Read local Nginx main config metadata and content.",
  },
  {
    name: "ngm.nginx.logs.tail",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Read recent local Nginx access or error log lines.",
  },
  {
    name: "ngm.proxy.list",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Compatibility tool for current ng-manager Nginx/proxy bindings.",
  },
  {
    name: "ngm.proxy.validate",
    skill: "ngm-nginx",
    capability: "nginx",
    riskLevel: "read",
    description: "Compatibility tool for validating Nginx/proxy config.",
  },
  {
    name: "ngm.task.list",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "List registered task views for a project, or active tasks when projectId is omitted.",
  },
  {
    name: "ngm.task.getStatus",
    skill: "ngm-project",
    capability: "project",
    riskLevel: "read",
    description: "Get the runtime status for a registered task.",
  },
  {
    name: "ngm.log.tail",
    skill: "ngm-project",
    capability: "logs",
    riskLevel: "read",
    description: "Read recent task logs by runId or taskId.",
  },
  {
    name: "ngm.log.search",
    skill: "ngm-workspace",
    capability: "logs",
    riskLevel: "read",
    description: "Search recent ng-manager system logs by keyword.",
  },
  {
    name: "ngm.git.status",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Read Git working tree status for a project when the core Git service is available.",
  },
  {
    name: "ngm.git.diff",
    skill: "ngm-workspace",
    capability: "workspace",
    riskLevel: "read",
    description: "Read Git diff for a project when the core Git service is available.",
  },
  {
    name: "hub_v2_projects_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List configured Hub V2 projects.",
  },
  {
    name: "hub_v2_projects_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one configured Hub V2 project.",
  },
  {
    name: "hub_v2_project_members_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 project members.",
  },
  {
    name: "hub_v2_docs_list",
    skill: "hub-v2-docs",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 project documents.",
  },
  {
    name: "hub_v2_docs_get",
    skill: "hub-v2-docs",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Read a Hub V2 project document by id.",
  },
  {
    name: "hub_v2_docs_get_by_slug",
    skill: "hub-v2-docs",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Read a Hub V2 project document by slug.",
  },
  {
    name: "hub_v2_issues_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 issues.",
  },
  {
    name: "hub_v2_issues_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one Hub V2 issue.",
  },
  {
    name: "hub_v2_issues_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_comment",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or add a Hub V2 issue comment with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_assign",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or assign a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_issues_update",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or update a Hub V2 issue with explicit confirmation.",
  },
  {
    name: "hub_v2_upload_markdown_image",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or upload a Markdown image for Hub V2 write workflows.",
  },
  {
    name: "hub_v2_rd_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List Hub V2 RD items.",
  },
  {
    name: "hub_v2_rd_get",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "Get one Hub V2 RD item.",
  },
  {
    name: "hub_v2_rd_stage_tasks_list",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "read",
    description: "List stage tasks for one Hub V2 RD item.",
  },
  {
    name: "hub_v2_rd_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create a Hub V2 RD item with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_advance_stage",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or advance a Hub V2 RD stage with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_stage_tasks_create",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or create Hub V2 RD stage tasks with explicit confirmation.",
  },
  {
    name: "hub_v2_rd_update_progress",
    skill: "hub-v2-api",
    capability: "hub-v2",
    riskLevel: "write",
    description: "Preview or update Hub V2 RD progress with explicit confirmation.",
  },
];

export const capabilityCatalog: CapabilityCatalogEntry[] = [
  {
    id: "routing",
    label: "Skill routing and MCP capability discovery",
    skills: ["ngm-router"],
    tools: ["ngm.capabilities", "ngm.routeTask"],
  },
  {
    id: "workspace",
    label: "Local ng-manager workspace, monorepo, package metadata, MCP tools, API debugging, design handoff, and CodeGraph availability",
    skills: ["ngm-workspace"],
    tools: [
      "ngm.workspace.summary",
      "ngm.workspace.listPackages",
      "ngm.workspace.getPackage",
      "ngm.workspace.mcpTools",
      "ngm.workspace.capabilityMap",
      "ngm.git.status",
      "ngm.git.diff",
      "ngm.log.search",
    ],
    notes: ["CodeGraph DB is not exposed directly by this MCP server in the current read-only phase."],
  },
  {
    id: "project",
    label: "Local project entries, package.json scripts, task views, process status, and logs",
    skills: ["ngm-project"],
    tools: [
      "ngm.project.list",
      "ngm.project.find",
      "ngm.project.get",
      "ngm.project.getScripts",
      "ngm.project.readPackageJson",
      "ngm.task.list",
      "ngm.task.getStatus",
      "ngm.log.tail",
    ],
  },
  {
    id: "runtime",
    label: "Node runtime, Node version manager, and project runtime resolution",
    skills: ["ngm-runtime"],
    tools: [
      "ngm.runtime.current",
      "ngm.runtime.list",
      "ngm.runtime.resolveForProject",
      "ngm.runtime.detectRequirement",
    ],
  },
  {
    id: "nginx",
    label: "Local Nginx status, server blocks, upstreams, config validation, and logs",
    skills: ["ngm-nginx"],
    tools: [
      "ngm.nginx.status",
      "ngm.nginx.servers.list",
      "ngm.nginx.server.get",
      "ngm.nginx.upstreams.list",
      "ngm.nginx.config.validate",
      "ngm.nginx.config.getMain",
      "ngm.nginx.logs.tail",
      "ngm.proxy.list",
      "ngm.proxy.validate",
    ],
  },
  {
    id: "hub-v2",
    label: "Hub V2 collaboration data: issues, RD workflows, documents, members, and uploads",
    skills: ["hub-v2-api", "hub-v2-docs"],
    tools: [
      "hub_v2_projects_list",
      "hub_v2_projects_get",
      "hub_v2_project_members_list",
      "hub_v2_docs_list",
      "hub_v2_docs_get",
      "hub_v2_docs_get_by_slug",
      "hub_v2_issues_list",
      "hub_v2_issues_get",
      "hub_v2_issues_create",
      "hub_v2_issues_comment",
      "hub_v2_issues_assign",
      "hub_v2_issues_update",
      "hub_v2_upload_markdown_image",
      "hub_v2_rd_list",
      "hub_v2_rd_get",
      "hub_v2_rd_stage_tasks_list",
      "hub_v2_rd_create",
      "hub_v2_rd_advance_stage",
      "hub_v2_rd_stage_tasks_create",
      "hub_v2_rd_update_progress",
    ],
  },
];

export const blockedLocalActions = [
  "run package scripts",
  "stop or restart local project processes",
  "install, uninstall, or switch Node versions",
  "change project runtime binding",
  "start, stop, or reload Nginx",
  "write Nginx config or proxy rules",
  "execute arbitrary shell commands",
];
