// This file is generated by apps/hub-v2/scripts/generate-upload-policies.mjs.
// Edit apps/hub-v2/shared/upload-policies.schema.json instead.

import type { UploadTargetPolicy } from './upload-policies';

export const UPLOAD_TARGETS = {
  "markdownImage": {
    "bucket": "temp",
    "category": "markdown",
    "visibility": "private",
    "accept": "image/*",
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg"
    ],
    "invalidTypeMessage": "仅支持图片文件",
    "sizeLimitMessage": "图片大小不能超过 10MB"
  },
  "commentImage": {
    "bucket": "temp",
    "category": "comment",
    "visibility": "private",
    "accept": "image/*",
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg"
    ],
    "invalidTypeMessage": "仅支持图片文件",
    "sizeLimitMessage": "评论图片不能超过 10MB"
  },
  "profileAvatar": {
    "bucket": "avatars",
    "category": "avatar",
    "visibility": "private",
    "accept": "image/*",
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg"
    ],
    "invalidTypeMessage": "仅支持图片文件",
    "sizeLimitMessage": "头像图片不能超过 10MB"
  },
  "projectAvatar": {
    "bucket": "project-avatars",
    "category": "project_avatar",
    "visibility": "private",
    "accept": "image/*",
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg"
    ],
    "invalidTypeMessage": "仅支持图片文件",
    "sizeLimitMessage": "图片大小不能超过 10MB"
  },
  "issueAttachment": {
    "bucket": "issues",
    "category": "attachment",
    "visibility": "private",
    "accept": "image/*,video/*,.png,.jpg,.jpeg,.gif,.webp,.bmp,.svg,.mp4,.mov,.webm,.mkv,.avi,.m4v,.flv,.wmv",
    "maxSizeBytes": 10485760,
    "allowedMimePrefixes": [
      "image/",
      "video/"
    ],
    "allowedExtensions": [
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".bmp",
      ".svg",
      ".mp4",
      ".mov",
      ".webm",
      ".mkv",
      ".avi",
      ".m4v",
      ".flv",
      ".wmv"
    ],
    "invalidTypeMessage": "仅支持上传图片或视频文件",
    "sizeLimitMessage": "单个文件最大 10MB"
  },
  "reimbursementAttachment": {
    "bucket": "reimbursements",
    "category": "attachment",
    "visibility": "private",
    "accept": "image/*,application/pdf,.jpg,.jpeg,.png,.pdf",
    "maxSizeBytes": 10485760,
    "allowedMimeTypes": [
      "image/jpeg",
      "image/png",
      "image/jpg",
      "application/pdf"
    ],
    "allowedExtensions": [
      ".jpg",
      ".jpeg",
      ".png",
      ".pdf"
    ],
    "invalidTypeMessage": "仅支持上传图片或 PDF 文件",
    "sizeLimitMessage": "单个文件最大 10MB"
  },
  "taskSheetAttachment": {
    "bucket": "task-sheets",
    "category": "attachment",
    "visibility": "private",
    "accept": "application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/pdf,image/jpeg,image/png,image/jpg,.doc,.docx,.pdf,.jpg,.jpeg,.png",
    "maxSizeBytes": 10485760,
    "allowedMimeTypes": [
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/pdf",
      "image/jpeg",
      "image/png",
      "image/jpg"
    ],
    "allowedExtensions": [
      ".doc",
      ".docx",
      ".pdf",
      ".jpg",
      ".jpeg",
      ".png"
    ],
    "invalidTypeMessage": "仅支持 Word / PDF / JPG / PNG 文件",
    "sizeLimitMessage": "单个文件最大 10MB"
  },
  "taskSheetWordImport": {
    "bucket": "task-sheets",
    "category": "word_import",
    "visibility": "private",
    "accept": "application/vnd.openxmlformats-officedocument.wordprocessingml.document,.docx",
    "maxSizeBytes": 10485760,
    "allowedMimeTypes": [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ],
    "allowedExtensions": [
      ".docx"
    ],
    "invalidTypeMessage": "仅支持 .docx 任务单文件",
    "sizeLimitMessage": "单个文件最大 10MB"
  }
} as const satisfies Record<string, UploadTargetPolicy>;

export const INLINE_VIDEO_EXTENSIONS = [
  ".mp4",
  ".webm",
  ".mov",
  ".m4v"
] as const;
