function generateBridgeScript() {
  return [
    "(function () {",
    "  if (window.__NGM_PREVIEW_DATA__) {",
    "    return;",
    "  }",
    "",
    "  function findHandoffElement(target) {",
    "    if (!target || !target.closest) return null;",
    "    return target.closest('[data-handoff-id]');",
    "  }",
    "",
    "  document.addEventListener('click', function (event) {",
    "    let el = findHandoffElement(event.target);",
    "    if (!el) return;",
    "    window.parent.postMessage({",
    "      type: 'ngm-handoff:select',",
    "      handoffId: el.getAttribute('data-handoff-id'),",
    "      handoffType: el.getAttribute('data-handoff-type') || 'layer',",
    "      layerId: el.getAttribute('data-layer-id') || '',",
    "      artboardId: el.getAttribute('data-artboard-id') || '',",
    "      source: 'ngm-preview'",
    "    }, '*');",
    "    event.preventDefault();",
    "    event.stopPropagation();",
    "  }, true);",
    "",
    "  window.addEventListener('message', function (event) {",
    "    let data = event.data || {};",
    "    if (data.type !== 'ngm-handoff:highlight') return;",
    "    let prev = document.querySelector('[data-ngm-handoff-selected=\"true\"]');",
    "    if (prev) {",
    "      prev.removeAttribute('data-ngm-handoff-selected');",
    "    }",
    "    let el = document.querySelector('[data-handoff-id=\"' + data.handoffId + '\"]');",
    "    if (!el) return;",
    "    el.setAttribute('data-ngm-handoff-selected', 'true');",
    "    el.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'center' });",
    "  });",
    "",
    "  window.parent.postMessage({ type: 'ngm-handoff:ready', source: 'ngm-preview' }, '*');",
    "})();",
    "",
  ].join("\n");
}

module.exports = {
  generateBridgeScript: generateBridgeScript,
};

export {};
