// Pure HTML Preview v2 的样式表。
// 提供图层树、设计稿 Stage、Inspect / 资源面板、screenshot 对照层的基础布局与交互样式。

function generatePreviewCss() {
  return [
    "* { box-sizing: border-box; }",
    "html, body { height: 100%; margin: 0; overflow: hidden; }",
    "body { font-family: -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif; background: #f5f5f5; color: #1f2937; }",
    "",
    ".ngm-preview-root { display: flex; flex-direction: column; height: 100vh; width: 100vw; }",
    ".ngm-preview-header { flex: 0 0 auto; display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 10px 12px; background: #fff; border-bottom: 1px solid #e5e7eb; font-size: 13px; }",
    ".ngm-preview-title { font-weight: 600; color: #1f2937; }",
    ".ngm-preview-toolbar { display: flex; gap: 8px; align-items: center; }",
    ".ngm-preview-toolbar button { background: #fff; border: 1px solid #d1d5db; border-radius: 4px; padding: 5px 10px; font-size: 12px; cursor: pointer; }",
    ".ngm-preview-toolbar button:hover { border-color: #3b82f6; color: #3b82f6; }",
    ".ngm-preview-toolbar button.active { background: #3b82f6; color: #fff; border-color: #3b82f6; }",
    "",
    ".ngm-preview-body { flex: 1 1 auto; display: flex; min-height: 0; }",
    ".ngm-panel { background: #fff; border: 1px solid #e5e7eb; display: flex; flex-direction: column; min-width: 0; }",
    ".ngm-panel-title { flex: 0 0 auto; padding: 10px 12px; font-size: 12px; font-weight: 600; border-bottom: 1px solid #f3f4f6; background: #fafafa; }",
    ".ngm-panel-content { flex: 1 1 auto; overflow: auto; padding: 8px; }",
    "",
    ".ngm-layer-tree { width: 300px; flex: 0 0 auto; border-right: none; }",
    ".ngm-layer-tree ul { list-style: none; margin: 0; padding: 0; }",
    ".ngm-layer-tree li { margin: 0; padding: 0; }",
    ".ngm-layer-tree-node { display: flex; align-items: center; gap: 6px; padding: 4px 6px; border-radius: 4px; cursor: pointer; font-size: 12px; white-space: nowrap; }",
    ".ngm-layer-tree-node:hover { background: #f0f5ff; }",
    ".ngm-layer-tree-node.selected { background: #e6f0ff; color: #3b82f6; }",
    ".ngm-layer-tree-node .toggle { width: 12px; height: 12px; display: inline-flex; align-items: center; justify-content: center; color: #999; }",
    ".ngm-layer-tree-node .icon { font-size: 10px; color: #999; }",
    ".ngm-layer-tree-node .name { overflow: hidden; text-overflow: ellipsis; }",
    ".ngm-layer-tree-children { padding-left: 16px; }",
    ".ngm-layer-tree-children.collapsed { display: none; }",
    "",
    ".ngm-stage-panel { flex: 1 1 auto; position: relative; background: #eef3f7; overflow: auto; }",
    ".ngm-stage-wrapper { position: relative; margin: 32px auto; background: #fff; box-shadow: 0 2px 14px rgba(15,23,42,0.12); transform-origin: top center; }",
    ".ngm-stage-content { position: relative; overflow: hidden; }",
    ".ngm-screenshot-layer { position: absolute; left: 0; top: 0; width: 100%; height: 100%; pointer-events: none; z-index: 1; background:#fff; }",
    ".ngm-screenshot-layer.hidden { display: none; }",
    ".ngm-screenshot-layer img { display: block; width: 100%; height: 100%; object-fit: fill; }",
    ".ngm-screenshot-missing { display:flex; align-items:center; justify-content:center; color:#9ca3af; font-size:13px; border:1px dashed #d1d5db; }",
    "",
    ".ngm-hotspot-layer { position:absolute; left:0; top:0; width:100%; height:100%; z-index:2; }",
    ".ngm-hotspot-layer.hidden { pointer-events:none; }",
    ".ngm-hotspot { position:absolute; cursor:pointer; background:rgba(59,130,246,0); border:1px solid transparent; }",
    ".ngm-hotspot:hover { border-color:#419bf9; background:rgba(65,155,249,0.08); }",
    ".ngm-hotspot-layer.hidden .ngm-hotspot { display:none; }",
    ".ngm-hotspot[data-ngm-handoff-selected='true'] { border:1px solid #ee6723 !important; background:rgba(238,103,35,0.08) !important; box-shadow:none !important; }",
    ".ngm-hotspot[data-ngm-handoff-selected='true']::before, .ngm-hotspot[data-ngm-handoff-selected='true']::after { position:absolute; display:block; padding:3px 5px; border-radius:2px; background:#ee6723; color:#fff; font-size:11px; line-height:12px; white-space:nowrap; z-index:4; }",
    ".ngm-hotspot[data-ngm-handoff-selected='true']::before { content:attr(data-width-label); left:50%; top:-21px; transform:translateX(-50%); }",
    ".ngm-hotspot[data-ngm-handoff-selected='true']::after { content:attr(data-height-label); right:-4px; top:50%; transform:translateX(100%) translateY(-50%); }",
    "",
    ".ngm-inspect-panel { width: 310px; flex: 0 0 auto; border-left: none; }",
    ".ngm-empty-state { color: #999; font-size: 12px; text-align: center; padding: 16px 8px; }",
    ".ngm-info-group { margin-bottom: 12px; }",
    ".ngm-info-label { font-size: 11px; color: #999; margin-bottom: 4px; }",
    ".ngm-info-value { font-size: 12px; color: #333; word-break: break-all; }",
    ".ngm-info-row { display: flex; justify-content: space-between; font-size: 12px; padding: 3px 0; border-bottom: 1px solid #f5f5f5; }",
    ".ngm-info-row > span:first-child { flex: 0 0 auto; color: #6b7280; padding-right: 12px; }",
    ".ngm-info-row > span:last-child { flex: 1 1 auto; text-align: right; word-break: break-all; }",
    ".ngm-color-swatch { display: inline-block; width: 12px; height: 12px; border-radius: 2px; border: 1px solid #e8e8e8; margin-right: 6px; vertical-align: middle; }",
    ".ngm-code-block { background: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 4px; padding: 8px; margin: 0; font-size: 11px; line-height: 1.5; white-space: pre-wrap; word-break: break-all; font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace; }",
    "",
    ".ngm-assets-panel { width: 280px; flex: 0 0 auto; border-left: none; }",
    ".ngm-asset-item { display: flex; gap: 8px; padding: 8px; border-radius: 4px; cursor: pointer; border-bottom: 1px solid #f5f5f5; }",
    ".ngm-asset-item:hover { background: #f0f5ff; }",
    ".ngm-asset-item.selected { background: #e6f0ff; }",
    ".ngm-asset-thumb { width: 32px; height: 32px; flex: 0 0 auto; background: #f5f5f5; border-radius: 4px; overflow: hidden; display: flex; align-items: center; justify-content: center; }",
    ".ngm-asset-thumb img { max-width: 100%; max-height: 100%; }",
    ".ngm-asset-meta { flex: 1; min-width: 0; }",
    ".ngm-asset-name { font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".ngm-asset-type { font-size: 11px; color: #999; }",
    "",
    "@media (max-width: 1100px) {",
    "  .ngm-layer-tree { width: 240px; }",
    "  .ngm-inspect-panel, .ngm-assets-panel { width: 240px; }",
    "}",
    "",
  ].join("\n");
}

module.exports = {
  generatePreviewCss: generatePreviewCss,
};

export {};
