export const McpErrorCodes = {
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_ROOT_NOT_FOUND: "PROJECT_ROOT_NOT_FOUND",
  PATH_ESCAPE_DENIED: "PATH_ESCAPE_DENIED",
  ABSOLUTE_PATH_DENIED: "ABSOLUTE_PATH_DENIED",
  CONFIRM_REQUIRED: "CONFIRM_REQUIRED",
  WRITE_NOT_ALLOWED: "WRITE_NOT_ALLOWED",
  EXECUTE_NOT_ALLOWED: "EXECUTE_NOT_ALLOWED",
  LOCAL_SERVER_UNAVAILABLE: "LOCAL_SERVER_UNAVAILABLE",
  TOOL_INPUT_INVALID: "TOOL_INPUT_INVALID",
} as const;

export type McpErrorCode = (typeof McpErrorCodes)[keyof typeof McpErrorCodes];
